# 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

# 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

np.show_config()

2.0.2
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
     

/Users/pboodida/Library/Python/3.9/lib/python/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


# 3. Create a null vector of size 10 (★☆☆)

In [4]:
z = np.zeros(10,dtype=int)

print(z)

[0 0 0 0 0 0 0 0 0 0]


# 4. How to find the memory size of any array (★☆☆)

In [5]:
print(z.nbytes)

80


# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10,dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


# 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
a=np.arange(10)
print(a[::-1])


[9 8 7 6 5 4 3 2 1 0]


# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = np.array([1,2,0,0,4,0])
ans=[]
for i in range(len(a)):
    if a[i]!=0:
        ans.append(i)
print(ans)
r=np.nonzero(a)
print(r)

[0, 1, 4]
(array([0, 1, 4]),)


# 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
a=np.identity(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
a=np.random.rand(3,3,3)
print(a)

[[[0.66410097 0.87773239 0.25983524]
  [0.2947705  0.65476947 0.83536157]
  [0.08688156 0.60005078 0.17684855]]

 [[0.10127997 0.04403186 0.30201572]
  [0.37279923 0.95222289 0.50401344]
  [0.76237931 0.62691641 0.10749647]]

 [[0.18132049 0.77699221 0.55927015]
  [0.68149152 0.33622836 0.98046853]
  [0.89203749 0.35351656 0.56132045]]]


# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.randint(10,100,(10,10))
print(a)
print("Maximum value is:",a.max())
print("Minimum value is:",a.min())

[[64 25 78 17 86 77 23 57 92 97]
 [80 42 77 68 68 20 27 74 26 22]
 [91 97 24 28 74 65 50 83 70 77]
 [96 22 18 34 90 77 58 56 49 73]
 [54 95 27 21 98 11 12 90 48 55]
 [45 45 21 58 30 90 24 68 42 28]
 [52 62 66 96 25 47 20 35 74 52]
 [42 17 88 81 12 49 28 53 97 67]
 [18 26 78 88 40 24 80 36 16 13]
 [16 94 38 44 30 12 61 65 45 83]]
Maximum value is: 98
Minimum value is: 11


# 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
a = np.random.randint(3,10,(3,10))
print(a)
print("The sum of values is:", a.sum())
print("The mean value is:", a.mean())

[[6 5 3 3 6 3 8 3 5 7]
 [7 9 9 3 7 8 6 4 4 6]
 [7 4 3 5 4 5 8 9 9 4]]
The sum of values is: 170
The mean value is: 5.666666666666667


# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
n=np.random.randint(2,6)
a = np.zeros((n,n),dtype=int)
a[0,:]=1
a[:,0]=1
a[-1,:]=1
a[:,-1]=1
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.random.randint(2,10,(3,3))
print(a)
x=np.zeros((a.shape[0]+2,a.shape[1]+2),dtype=int)
x[1:-1,1:-1]=a
print(x)
b=np.pad(a,1,mode='constant')
print(b)

[[4 4 6]
 [3 2 8]
 [6 4 4]]
[[0 0 0 0 0]
 [0 4 4 6 0]
 [0 3 2 8 0]
 [0 6 4 4 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 4 4 6 0]
 [0 3 2 8 0]
 [0 6 4 4 0]
 [0 0 0 0 0]]


# 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
a=np.diag((1,2,3,4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8,8), dtype=int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [23]:
a=np.random.rand(6,7,8)
print(a)
a.size
np.unravel_index(99,(6,7,8))

[[[2.05137835e-01 7.50371994e-01 9.09051905e-01 7.27739446e-01
   5.25159082e-01 5.44792784e-01 6.88574175e-01 1.40876385e-01]
  [7.93248644e-01 4.26510135e-01 9.86786931e-01 6.50643363e-01
   5.23200350e-01 1.34442434e-01 5.44624372e-01 7.14705524e-02]
  [5.84654246e-01 4.30176946e-04 7.07262645e-01 2.07992320e-01
   9.46282277e-01 9.16038198e-01 9.44604054e-01 8.70860841e-01]
  [2.55484994e-01 9.64978068e-01 9.90486086e-01 8.09217979e-01
   1.28419129e-01 6.99965960e-01 6.51378257e-01 9.47869610e-01]
  [9.53491742e-01 2.92675773e-01 7.12083655e-01 3.74122403e-01
   7.81292938e-01 5.06341991e-01 4.80857693e-01 1.84739656e-01]
  [1.94686042e-01 9.17824706e-01 4.16448115e-01 9.45832417e-01
   6.27797945e-01 5.19249914e-01 5.20688211e-01 1.58121228e-01]
  [2.92129381e-01 3.08974950e-01 8.87637449e-01 1.94191074e-01
   6.76356911e-01 9.20359443e-01 3.10301171e-01 9.65549500e-01]]

 [[9.79641364e-01 6.25629427e-01 3.55821928e-01 4.06859679e-01
   4.57405676e-01 6.48430893e-01 3.25848123e-0

(np.int64(1), np.int64(5), np.int64(3))

# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [29]:
a=np.array([[0,1],[1,0]])
print(a)
checkerboard=np.tile(a,(4,4))
print(checkerboard)


[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 22. Normalize a 5x5 random matrix (★☆☆)


In [30]:
a = np.random.random((5,5))
a_min = a.min()
a_max = a.max()
normalized = (a - a_min) / (a_max - a_min)
print(normalized)

[[0.42983564 0.86889956 0.40053995 0.62183507 0.58378163]
 [0.14912203 0.73504729 0.76866817 0.26923602 0.87414322]
 [0.08521964 0.98927649 1.         0.46920209 0.94450361]
 [0.41059666 0.42176895 0.04143613 0.         0.07135519]
 [0.55569342 0.95750392 0.22331727 0.12741857 0.05649775]]


# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [31]:
color_dtype = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])
print(color_dtype)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [35]:
a= np.random.random((5,3))
b= np.random.random((3,2))
c= np.dot(a, b)
print(c.shape)
print(c)

(5, 2)
[[0.64685433 0.9247158 ]
 [0.42938796 0.68664645]
 [0.26607346 0.42196024]
 [0.50094575 1.17696891]
 [0.48857847 1.30672117]]


# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [36]:
a=np.arange(10)
print(a)
a[(a>3) & (a<8)]*=-1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


# 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

# Valid
# Valid
# Invalid
# Valid
# Valid
# valid but error occurs  


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [38]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/pp/dqdqbjt97c59y9lw190p5yf00000gn/T/ipykernel_24179/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/pp/dqdqbjt97c59y9lw190p5yf00000gn/T/ipykernel_24179/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/pp/dqdqbjt97c59y9lw190p5yf00000gn/T/ipykernel_24179/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


# 29. How to round away from zero a float array ? (★☆☆)

In [41]:
a=np.random.rand(3,3)
print(a)
a=np.round(a)
print(a)

[[0.45706601 0.36732302 0.53006701]
 [0.90727278 0.17580834 0.88231518]
 [0.40161388 0.01816974 0.84296012]]
[[0. 0. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]


# 30. How to find common values between two arrays? (★☆☆)

In [46]:
a=np.random.randint(2,6,(1,5))
b=np.random.randint(2,6,(1,5))
print(a)
print(b)
common=np.intersect1d(a,b)
print(common)

[[5 4 2 3 2]]
[[5 2 2 3 5]]
[2 3 5]


# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# 32. Is the following expressions true? (★☆☆)


In [ ]:
np.seterr(all='ignore')
print(np.sqrt(-1)==np.emath.sqrt(-1)) #nan==1j

False


# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [49]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2026-02-11 2026-02-12 2026-02-13


# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [50]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [51]:
a=np.ones(5)
b=np.ones(5)
np.add(a,b,out=a)
np.divide(a,-2,out=b)
np.multiply(a,b,out=a)
print(a)

[-2. -2. -2. -2. -2.]


# 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [54]:
a = np.random.uniform(0, 10, 5)
print(a)
print(a.astype(int))
print(np.trunc(a))
print(np.ceil(a))
print(np.floor(a))
print(a // 1)


[6.81683333 0.62045269 5.19420137 4.39904831 9.29428344]
[6 0 5 4 9]
[6. 0. 5. 4. 9.]
[ 7.  1.  6.  5. 10.]
[6. 0. 5. 4. 9.]
[6. 0. 5. 4. 9.]


# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [57]:
a = np.tile(np.arange(5), (5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [58]:
def my_generator():
    for i in range(10):
        yield i
arr = np.array(list(my_generator()))
print(arr)


[0 1 2 3 4 5 6 7 8 9]


# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [60]:
a = np.linspace(0, 1, 12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 40. Create a random vector of size 10 and sort it (★★☆)

In [61]:
a=np.random.rand(10)
print(a)
a.sort()
print(a)

[0.95422306 0.19483609 0.17328719 0.8129996  0.21965501 0.09946361
 0.6871951  0.92187413 0.33136825 0.22538844]
[0.09946361 0.17328719 0.19483609 0.21965501 0.22538844 0.33136825
 0.6871951  0.8129996  0.92187413 0.95422306]


In [62]:
# 41. How to sum a small array faster than np.sum? (★★☆)
a = np.arange(10)
print(sum(a))

45


In [72]:
#### 42. Consider two random arrays A and B, check if they are equal (★★☆)
A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)
np.array_equal(A, B)

False

In [74]:
#### 43. Make an array immutable (read-only) (★★☆)
Z = np.arange(10)
Z.flags.writeable = False
Z[1]=5

ValueError: assignment destination is read-only

In [75]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10, 2))
x = Z[:, 0]
y = Z[:, 1]
r = np.sqrt(x**2 + y**2)
theeta = np.arctan2(y, x)
polar = np.column_stack((r, theeta))

In [77]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.93835644 0.76987264 0.32797374 0.96340874 0.929499   0.50089244
 0.18066924 0.04568871 0.28212992 0.52028314]
[0.93835644 0.76987264 0.32797374 0.         0.929499   0.50089244
 0.18066924 0.04568871 0.28212992 0.52028314]


In [79]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
Z = np.zeros((10, 10), dtype=[('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(
    np.linspace(0, 1, 10),
    np.linspace(0, 1, 10)
)
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [81]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
X = np.arange(5)
Y = np.arange(5) + 0.5
C = 1.0 / (X[:, None] - Y[None, :])
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


In [82]:
#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(dtype, np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float64]:
    print(dtype, np.finfo(dtype).min, np.finfo(dtype).max)


<class 'numpy.int8'> -128 127
<class 'numpy.int16'> -32768 32767
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.float16'> -65500.0 65500.0
<class 'numpy.float32'> -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> -1.7976931348623157e+308 1.7976931348623157e+308


In [ ]:
#### 49. How to print all the values of an array? (★★☆)
Z = np.arange(100)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.random.random(10)
value = 0.5
closest = Z[np.abs(Z - value).argmin()]

In [86]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
dtype = np.dtype([
    ('position', [('x', float), ('y', float)]),
    ('color', [('r', float), ('g', float), ('b', float)])
])
Z = np.zeros(1, dtype=dtype)
Z['position']['x'] = 1.0
Z['color']['r'] = 255
print(Z)

[((1., 0.), (255., 0., 0.))]


In [91]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((100, 2))
distances = np.sqrt(((Z[1:] - Z[:-1])**2).sum(axis=1))
print(distances)
print(distances.shape)

[0.88985571 0.48222107 0.45420509 0.60720881 0.58611787 0.63454369
 0.43370309 0.28187171 0.55273351 0.84920102 0.78433003 0.81857967
 0.43745212 0.57248041 0.91662975 0.93071181 0.17805249 0.39562874
 0.53026103 0.76071813 0.25373486 0.29198268 0.8051762  0.75560573
 0.69518904 0.15589454 0.43070788 0.4268829  0.45296818 0.53723734
 0.26432799 0.19909801 0.27105255 0.36105439 0.62708174 0.28239902
 0.26274915 1.07149441 0.07058482 0.55363678 0.30076366 0.18900994
 0.41158681 0.96552699 0.79655595 0.27461404 0.31487619 0.81132695
 0.71064656 0.69018293 0.08928527 0.38068819 0.59669457 0.77801484
 0.88854937 0.16683555 0.89815537 0.7687924  0.23910477 0.14842912
 0.22085375 0.36491566 0.56035987 0.62834753 0.44421315 0.93089103
 0.25404138 0.74993565 0.90872651 0.68537912 0.77805062 0.87259856
 0.45850794 0.15000671 0.65821922 0.53747581 0.97166525 0.08482357
 0.40291923 0.41684312 0.81408304 0.93890411 0.34972165 0.27137076
 0.60108055 0.47358832 0.44112677 0.59336521 0.62280956 0.1302

In [93]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
Z.dtype

dtype('int32')

In [94]:
#### 54. How to read the following file? (★★☆)
'''
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
'''
from io import StringIO
data = StringIO("""
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
""")
Z = np.genfromtxt(data, delimiter=",")
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [95]:
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Z = np.arange(5)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4


In [103]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)
size = 5
sigma = 1.0
ax = np.linspace(-(size//2), size//2, size)
xx, yy = np.meshgrid(ax, ax)
gaussian = np.exp(-(xx**2 + yy**2) / (2*sigma**2))
print(np.round(gaussian, 3))


[[0.018 0.082 0.135 0.082 0.018]
 [0.082 0.368 0.607 0.368 0.082]
 [0.135 0.607 1.    0.607 0.135]
 [0.082 0.368 0.607 0.368 0.082]
 [0.018 0.082 0.135 0.082 0.018]]


In [107]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)
Z = np.zeros((10, 10))
p = 5
indices = np.random.choice(Z.size, p, replace=False)
Z.flat[indices] = 1
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [109]:
#### 58. Subtract the mean of each row of a matrix (★★☆)
Z = np.random.random((5, 5))
print(Z)
Z -= Z.mean(axis=1, keepdims=True)
print(Z)

[[0.92228486 0.46527661 0.66925339 0.57102092 0.80247025]
 [0.37046204 0.56972318 0.80826366 0.53327654 0.01938713]
 [0.14539018 0.88943052 0.87318328 0.39050515 0.78694714]
 [0.31719698 0.82498801 0.4448796  0.55029391 0.92997806]
 [0.86207093 0.55728232 0.73603797 0.40169164 0.47977506]]
[[ 0.23622365 -0.22078459 -0.01680782 -0.11504028  0.11640905]
 [-0.08976047  0.10950067  0.34804115  0.07305404 -0.44083538]
 [-0.47170108  0.27233926  0.25609203 -0.2265861   0.16985589]
 [-0.29627034  0.2115207  -0.16858771 -0.0631734   0.31651075]
 [ 0.25469935 -0.05008926  0.12866639 -0.20567994 -0.12759653]]


In [112]:
#### 59. How to sort an array by the nth column? (★★☆)
Z = np.random.random((5, 5))
n = 2
print(Z)
Z_sorted = Z[Z[:, n].argsort()]
print(Z_sorted)

[[0.09775069 0.41795466 0.97121016 0.19363094 0.99640733]
 [0.37186051 0.64900306 0.01093036 0.30492262 0.7844154 ]
 [0.3346985  0.47649864 0.24870817 0.89593818 0.92547688]
 [0.60908682 0.35451853 0.28322533 0.63158484 0.35806384]
 [0.16924861 0.01656133 0.11650638 0.99829988 0.07475403]]
[[0.37186051 0.64900306 0.01093036 0.30492262 0.7844154 ]
 [0.16924861 0.01656133 0.11650638 0.99829988 0.07475403]
 [0.3346985  0.47649864 0.24870817 0.89593818 0.92547688]
 [0.60908682 0.35451853 0.28322533 0.63158484 0.35806384]
 [0.09775069 0.41795466 0.97121016 0.19363094 0.99640733]]


In [113]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)
Z = np.random.randint(0, 2, (5, 5))
null_columns = np.all(Z == 0, axis=0)
print(null_columns)

[False False False False False]


In [115]:
#### 61. Find the nearest value from a given value in an array (★★☆)
Z = np.random.random(10)
x = 0.5
nearest = Z[np.abs(Z - x).argmin()]
print(nearest)

0.41882348746375175


In [116]:
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
it = np.nditer([A, B, None])
C = A + B 
print(C)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [117]:
#### 63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
Z = NamedArray([1,2,3], name="MyArray")
print(Z.name)

MyArray


In [118]:
#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
Z = np.zeros(5)
I = [0, 1, 1, 3]
np.add.at(Z, I, 1)
print(Z)

[1. 2. 0. 1. 0.]


In [119]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
X = np.array([1,2,3,4])
I = np.array([0,1,0,1])
F = np.zeros(2)
np.add.at(F, I, X)
print(F)

[4. 6.]


In [120]:
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
Z = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)
colors = np.unique(Z.reshape(-1, 3), axis=0)
n_colors = len(colors)
print(n_colors)

9998


In [121]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
Z = np.random.random((3,4,5,6))
result = Z.sum(axis=(-2, -1))
print(result)

[[15.14753498 12.48938283 16.45839208 13.22653564]
 [15.39925285 15.34632196 15.90215148 14.82664634]
 [13.94750707 17.9698242  16.2031994  14.850775  ]]


In [122]:
#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
D = np.array([10,20,30,40,50])
S = np.array([0,0,1,1,1])
means = np.bincount(S, weights=D) / np.bincount(S)
print(means)

[15. 40.]


In [124]:
#### 69. How to get the diagonal of a dot product? (★★★)
A=np.random.random((3,3))
B=np.random.random((3,3))
np.sum(A * B.T, axis=1)


array([1.11716854, 1.19031093, 1.48731263])

In [125]:
#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
Z = np.array([1,2,3,4,5])
result = np.zeros(len(Z)*4 - 3, dtype=Z.dtype)
result[::4] = Z
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [127]:
#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)
Z = np.ones((5,5,3))
M = np.ones((5,5))
result = Z * M[..., None]
print(result)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [128]:
#### 72. How to swap two rows of an array? (★★★)
Z[[0,1]] = Z[[1,0]]

In [129]:
#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
triangles = np.random.randint(0,10,(10,3))
edges = np.vstack([
    triangles[:,[0,1]],
    triangles[:,[1,2]],
    triangles[:,[2,0]]
])
# Sort each edge to remove direction
edges = np.sort(edges, axis=1)
# Unique edges
edges = np.unique(edges, axis=0)
print(edges)

[[0 3]
 [0 6]
 [0 7]
 [0 9]
 [1 6]
 [1 7]
 [1 8]
 [2 2]
 [2 7]
 [3 7]
 [3 9]
 [6 7]
 [6 8]
 [7 7]
 [7 9]]


In [131]:
#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
C = np.array([2,3,1])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 1 1 1 2]


In [133]:
#### 75. How to compute averages using a sliding window over an array? (★★★)
Z = np.arange(10)
window = 3
result = np.convolve(Z, np.ones(window)/window, mode='valid')
print(result)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [135]:
#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
Z = np.arange(10)
result = np.lib.stride_tricks.sliding_window_view(Z, 3)
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [137]:
#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
Z = np.array([True, False])
Z ^= True
print(Z)

[False  True]


In [141]:
#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
P0 = np.random.random((5,2))
P1 = np.random.random((5,2))
p  = np.random.random(2)
# Direction vectors of lines
V = P1 - P0              # (5,2)
# Vector from line start to point
W = p - P0               # (5,2)
# Manual 2D cross product
cross = V[:,0]*W[:,1] - V[:,1]*W[:,0]
# Distance formula
dist = np.abs(cross) / np.linalg.norm(V, axis=1)
print(dist)

[0.31573403 0.29293181 0.28310858 0.18757601 0.15946887]


In [ ]:
#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
P  = np.random.random((4,2))   # 4 points
P0 = np.random.random((5,2))   # 5 line starts
P1 = np.random.random((5,2))   # 5 line ends
# Line direction vectors
V = P1 - P0                 # (5,2)
# Vector from line start to each point
W = P[None,:,:] - P0[:,None,:]   # (5,4,2)
# 2D cross product manually
cross = V[:,None,0]*W[:,:,1] - V[:,None,1]*W[:,:,0]
# Distance formula
dist = np.abs(cross) / np.linalg.norm(V, axis=1)[:,None]
print(dist.shape)   # (5,4)

(5, 4)


In [142]:
#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
def extract_centered(arr, center, shape, fill=0):
    arr = np.asarray(arr)
    center = np.asarray(center)
    shape = np.asarray(shape)
    # Compute half window sizes
    half = shape // 2
    # Start & end indices in original array
    start = center - half
    end   = start + shape
    # Amount of padding needed
    pad_before = np.maximum(0, -start)
    pad_after  = np.maximum(0, end - arr.shape)
    # Clip slicing indices to valid range
    start = np.maximum(0, start)
    end   = np.minimum(arr.shape, end)
    # Slice the valid part
    sliced = arr[tuple(slice(s, e) for s, e in zip(start, end))]
    # Pad if needed
    if np.any(pad_before) or np.any(pad_after):
        pad_width = list(zip(pad_before, pad_after))
        sliced = np.pad(sliced, pad_width, constant_values=fill)
    return sliced
Z = np.arange(25).reshape(5,5)
result = extract_centered(Z, center=(0,0), shape=(3,3), fill=-1)
print(result)

[[-1 -1 -1]
 [-1  0  1]
 [-1  5  6]]


In [143]:
#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
Z = np.arange(1,15)
R = np.lib.stride_tricks.sliding_window_view(Z, 4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [145]:
#### 82. Compute a matrix rank (★★★)
A=np.random.random((3,3))
np.linalg.matrix_rank(A)

np.int64(3)

In [147]:
#### 83. How to find the most frequent value in an array?
vals, counts = np.unique(Z, return_counts=True)
most_frequent = vals[np.argmax(counts)]
print(most_frequent)

1


In [159]:
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
Z = np.random.random((10,10))
blocks = np.lib.stride_tricks.sliding_window_view(Z, (3,3))
print(blocks.shape)

(8, 8, 3, 3)


In [160]:
#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i,j), value)
        super().__setitem__((j,i), value)
Z = np.zeros((5,5)).view(SymmetricArray)
Z[1,3]=7
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [162]:
#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
p,n=3,4
A=np.random.random((p,n,n))
B=np.random.random((p,n,1))
result = np.einsum('pij,pjk->ik', A, B)
print(result.shape)

(4, 1)


In [163]:
#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
Z=np.random.random((16,16))
block_sum=Z.reshape(4,4,4,4).sum(axis=(2,3))
print(block_sum)

[[6.76861268 7.47664167 7.16697537 8.64332953]
 [6.32310016 9.81284188 9.03765434 9.12097923]
 [7.11523354 9.54580451 9.22075691 8.46194009]
 [7.04052914 6.98422629 7.83352021 8.62263607]]


In [164]:
#### 88. How to implement the Game of Life using numpy arrays? (★★★)
def game_of_life(Z):
    N = sum(np.roll(np.roll(Z,i,0),j,1)
            for i in (-1,0,1)
            for j in (-1,0,1)
            if (i,j)!=(0,0))
    return (N==3) | (Z & (N==2))
Z = np.random.randint(0,2,(5,5))
print(game_of_life(Z))

[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 1]
 [0 1 0 0 0]]


/var/folders/pp/dqdqbjt97c59y9lw190p5yf00000gn/T/ipykernel_24179/2123863108.py:3: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  N = sum(np.roll(np.roll(Z,i,0),j,1)


In [165]:
#### 89. How to get the n largest values of an array (★★★)
Z = np.random.randint(0,100,20)
n = 5
idx = np.argpartition(Z, -n)[-n:]
print(Z[idx])

[71 81 83 99 88]


In [166]:
#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)
def cartesian(arrays):
    return np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))
print(cartesian(([1,2], [3,4], [5,6])))

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


In [167]:
#### 91. How to create a record array from a regular array? (★★★)
Z = np.array([(1,2.), (3,4.)])
R = np.core.records.fromarrays(Z.T, names='a,b')
print(R)

[(1., 2.) (3., 4.)]


/var/folders/pp/dqdqbjt97c59y9lw190p5yf00000gn/T/ipykernel_24179/1573974196.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T, names='a,b')


In [168]:
#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
Z = np.array([1,2,3,4])
print(Z**3)
print(Z*Z*Z)
print(np.power(Z,3))

[ 1  8 27 64]
[ 1  8 27 64]
[ 1  8 27 64]


In [169]:
#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
A = np.array([[1,2,3],[4,5,6],[3,2,1]])
B = np.array([[1,2,3],[6,5,4]])
A_sorted = np.sort(A, axis=1)
B_sorted = np.sort(B, axis=1)
mask = (A_sorted[:,None,:] == B_sorted[None,:,:]).all(-1)
print(A[mask.any(axis=1)])

[[1 2 3]
 [4 5 6]
 [3 2 1]]


In [170]:
#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
Z = np.array([[2,2,3],[4,4,4],[1,2,3]])
rows = Z[np.any(Z != Z[:,[0]], axis=1)]
print(rows)

[[2 2 3]
 [1 2 3]]


In [171]:
#### 95. Convert a vector of ints into a matrix binary representation (★★★)
Z = np.array([3,5,6])
binary = ((Z[:,None] & (1 << np.arange(4))) > 0).astype(int)
print(binary)

[[1 1 0 0]
 [1 0 1 0]
 [0 1 1 0]]


In [173]:
#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
Z = np.array([[1,2],[1,2],[3,4]])
print(np.unique(Z, axis=0))

[[1 2]
 [3 4]]


In [174]:
#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
A = np.array([1,2,3])
B = np.array([4,5,6])
print("Inner:", np.einsum('i,i->', A, B))
print("Outer:\n", np.einsum('i,j->ij', A, B))
print("Sum:", np.einsum('i->', A))
print("Mul:", np.einsum('i,i->i', A, B))

Inner: 32
Outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum: 6
Mul: [ 4 10 18]


In [175]:
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
X = np.linspace(0,10,10)
Y = np.sin(X)
dist = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumdist = np.insert(np.cumsum(dist), 0, 0)
new_dist = np.linspace(0, cumdist[-1], 20)
X_new = np.interp(new_dist, cumdist, X)
Y_new = np.interp(new_dist, cumdist, Y)
print(X_new)
print(Y_new)

[ 0.          0.49460368  0.98920735  1.58796909  2.22079915  2.69648165
  3.17180996  3.67759214  4.1990497   4.76927687  5.38285581  5.88901294
  6.35309115  6.84641868  7.40068779  7.96384943  8.54593703  9.07823137
  9.53911568 10.        ]
[ 0.          0.39893396  0.79786792  0.85285777  0.79534938  0.37445273
 -0.04726293 -0.43030092 -0.79343054 -0.87684168 -0.71160853 -0.35320967
  0.08085543  0.47492956  0.78568164  0.91562772  0.66076475  0.33088859
 -0.10656626 -0.54402111]


In [176]:
#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
def multinomial_rows(X, n):
    """
    Select rows that:
    1) contain only integers
    2) sum to n
    """
    # Check integer condition
    integer_mask = np.all(np.equal(np.mod(X, 1), 0), axis=1)
    # Check sum condition
    sum_mask = np.sum(X, axis=1) == n
    return X[integer_mask & sum_mask]
# Example
n = 5
X = np.array([
    [2, 1, 2],
    [1, 1, 1],
    [3, 1, 1],
    [2.5, 1, 1],
    [0, 5, 0]
])
print("Input:\n", X)
print("Valid multinomial rows (sum = 5):\n", multinomial_rows(X, n))

Input:
 [[2.  1.  2. ]
 [1.  1.  1. ]
 [3.  1.  1. ]
 [2.5 1.  1. ]
 [0.  5.  0. ]]
Valid multinomial rows (sum = 5):
 [[2. 1. 2.]
 [3. 1. 1.]
 [0. 5. 0.]]


In [177]:
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
def bootstrap_mean_ci(X, N=10000, ci=95):
    """
    Compute bootstrap confidence interval for mean.
    
    X  : 1D array
    N  : number of bootstrap samples
    ci : confidence level (default 95)
    """
    X = np.asarray(X)
    n = len(X)
    # Generate bootstrap samples (with replacement)
    samples = np.random.choice(X, size=(N, n), replace=True)
    # Compute means
    means = samples.mean(axis=1)
    # Compute confidence interval
    lower = np.percentile(means, (100-ci)/2)
    upper = np.percentile(means, 100-(100-ci)/2)
    return lower, upper
# Example
X = np.random.normal(loc=10, scale=2, size=100)
lower, upper = bootstrap_mean_ci(X)
print("Mean:", np.mean(X))
print("95% CI:", (lower, upper))

Mean: 9.796453946950011
95% CI: (np.float64(9.383944725887293), np.float64(10.205482357592688))
